# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy Frontend (Docker)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: aw5145-dashboard

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 1. checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. setup buildx
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. login to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug â€” list frontend files
        run: ls -R frontend

      # 4. build & push FE image
      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/sukumaporn2546/aw5145-dashboard:latest
            ghcr.io/sukumaporn2546/aw5145-dashboard:${{ github.sha }}

      # 5. copy compose to VM
      - name: Copy docker-compose to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "./frontend/compose.yml"
          target: "~/frontend-app"

      # 6. deploy on VM
      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/frontend-app

            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            # generate .env on VM (à¸–à¹‰à¸²à¸¡à¸µ env à¸ªà¸³à¸«à¸£à¸±à¸š FE)
            cat > .env << EOF
            VITE_THINGSBOARD_HOST_WEBSOCKET=${{ secrets.VITE_THINGSBOARD_HOST }}
            VITE_THINGSBOARD_HOST=${{ secrets.VITE_THINGSBOARD_HOST }}
            VITE_USERNAME=${{ secrets.VITE_USERNAME }}
            VITE_PASSWORD=${{ secrets.VITE_PASSWORD }}
            VITE_DEVICE_ID=${{ secrets.VITE_DEVICE_ID }}
            VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}
            EOF

            docker compose pull
            docker compose up -d --remove-orphans

            docker image prune -af --filter "until=24h"

            echo "ðŸš€ Frontend deployed successfully!"
